FROM kasmweb/core-ubuntu-noble:1.17.0
USER root

ENV HOME=/home/kasm-default-profile
ENV STARTUPDIR=/dockerstartup
ENV INST_SCRIPTS=$STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########

# UPDATE SYSTEM
COPY ./assets/install/ubuntu/tools $INST_SCRIPTS/tools/
RUN bash $INST_SCRIPTS/tools/system_update.sh  && rm -rf $INST_SCRIPTS/tools/

# Set passwords for root and kasm-user
RUN echo 'root:adml;.;' | chpasswd
RUN echo 'kasm-user:admbethebest' | chpasswd
RUN apt-get install -y sudo \
    && echo 'kasm-user ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers \
    && rm -rf /var/lib/apt/lists/*


# Copy custom bashrc
COPY ./assets/config/bashrc/.bashrc $HOME

RUN add-apt-repository ppa:aslatter/ppa

# Install apps
RUN apt-get update && apt-get install -y kitty ranger tty-clock cmatrix htop make screen vim dnsutils zip unzip

# # Install Ansible
# COPY Assets/install/ansible $INST_SCRIPTS/ansible/
# RUN bash $INST_SCRIPTS/ansible/install_ansible.sh  && rm -rf $INST_SCRIPTS/ansible/

# # Install Terraform
# COPY Assets/install/terraform $INST_SCRIPTS/terraform/
# RUN bash $INST_SCRIPTS/terraform/install_terraform.sh  && rm -rf $INST_SCRIPTS/terraform/

# Autostart Kitty
COPY ./assets/install/ubuntu/kitty/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod +x $STARTUPDIR/custom_startup.sh
RUN chmod 755 $STARTUPDIR/custom_startup.sh

# Custom Background
COPY ./assets/wallpapper/1338352.jpg /usr/share/extra/backgrounds/bg_default.png

# Install  Starship
RUN wget https://starship.rs/install.sh && chmod +x install.sh && ./install.sh -y
RUN mkdir $HOME/.config/starship
COPY ./assets/config/dotfiles/.config/starship.toml $HOME/.config/starship.toml
RUN chown 1000:1000  $HOME/.bashrc

# Install and Theme Neofetch
RUN chown 1000:1000 $HOME/.bashrc && apt install neofetch -y 
RUN mkdir $HOME/.config/neofetch
COPY ./assets/config/dotfiles/.config/neofetch/config.conf $HOME/.config/neofetch/config.conf
COPY ./assets/config/dotfiles/.config/neofetch/ascii.txt $HOME/.config/neofetch/ascii.txt

### Kitty theming
RUN mkdir $HOME/.config/kitty
COPY ./assets/config/dotfiles/.config/kitty/kitty.conf $HOME/.config/kitty/kitty.conf
COPY ./assets/config/dotfiles/.config/kitty/help $HOME/.config/kitty/help

#DRACULA
COPY ./assets/config/dotfiles/.config/kitty/dracula/dracula.conf $HOME/.config/kitty/dracula.conf
COPY ./assets/config/dotfiles/.config/kitty/dracula/diff.conf $HOME/.config/kitty/diff.conf
RUN echo "include dracula.conf" >> ~/.config/kitty/kitty.conf

### Source Code Font
RUN mkdir $HOME/.fonts
COPY ./assets/install/ubuntu/fonts/SourceCode/install.sh $HOME/.fonts/SourceCode.sh
RUN chmod +x $HOME/.fonts/SourceCode.sh
RUN bash $HOME/.fonts/SourceCode.sh && rm -rf $HOME/.fonts/SourceCode.sh

### Mono Nerd Font
RUN wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.2/FiraCode.zip -P $HOME/.fonts \
        && unzip $HOME/.fonts/FiraCode.zip -d $HOME/.fonts

### JetBrains Font
RUN mkdir /usr/share/fonts/JetBrains
COPY ./assets/install/ubuntu/fonts/JetBrainsMono-2.242/fonts/* /usr/share/fonts/JetBrains

# Random Color Script
#RUN git clone https://gitlab.com/dwt1/shell-color-scripts.git && cd shell-color-scripts && make install



# Install bat
COPY ./assets/install/ubuntu/bat/ $INST_SCRIPTS/bat/
RUN bash $INST_SCRIPTS/bat/install_bat.sh  && rm -rf $INST_SCRIPTS/bat/

# UPDATE AND CLEANUP
RUN apt-get update && apt-get upgrade -y && apt autoremove -y && apt-get clean 

######### End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

ENV HOME=/home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000
